version: '3'
services:
  redis_db:
    image: redis:4.0
    volumes:
      - data:/data
  script:
    image: ifyouseewendy/star-reminder:0.1
    build: .
    volumes:
      - .:/app
    env_file:
      - ./.production.env
    depends_on:
      - redis_db
volumes:
  data:
