version: '3.1'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
  redis_db:
    image: redis:4.0
    volumes:
      - data:/data
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
  dogstatsd:
    image: datadog/docker-dd-agent:latest
    ports:
      - "8125:8125/udp"
    environment:
      - SD_BACKEND=docker
      - API_KEY=${DATADOG_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"
  app:
    image: ifyouseewendy/star-reminder:latest
    ports:
      - "9393:9393"
    environment:
      - RACK_ENV=production
      - REDIS_HOST=redis://redis_db:6379
      - DATADOG_HOST=dogstatsd:8125
      - ENV_PRODUCTION=/run/secrets/env_production
    depends_on:
      - redis_db
      - dogstatsd
    secrets:
      - env_production
    logging:
      driver: syslog
      options:
        tag: "{{.Name}}/{{.ID}}"

volumes:
  data:
  bundle:

secrets:
   env_production:
     file: /opt/.env.production
