version: '3.1'
services:
  nginx:
    image: jwilder/nginx-proxy:alpine
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
    logging:
      driver: splunk
      options:
        splunk-token: BC18A09D-DFC8-4E97-A7A4-27001DA1B9F4
        splunk-url: "https://localhost:8088"
        splunk-insecureskipverify: "true"
        tag: "{{.Name}}/{{.FullID}}"
  redis_db:
    image: redis:4.0
    volumes:
      - data:/data
    logging:
      driver: splunk
      options:
        splunk-token: BC18A09D-DFC8-4E97-A7A4-27001DA1B9F4
        splunk-url: "https://localhost:8088"
        splunk-insecureskipverify: "true"
        tag: "{{.Name}}/{{.FullID}}"
  app:
    image: ifyouseewendy/star-reminder:latest
    ports:
      - "9393:9393"
    environment:
      - RACK_ENV=production
      - REDIS_HOST=redis://redis_db:6379
      - ENV_PRODUCTION=/run/secrets/env_production
    secrets:
      - env_production
    logging:
      driver: splunk
      options:
        splunk-token: BC18A09D-DFC8-4E97-A7A4-27001DA1B9F4
        splunk-url: "https://localhost:8088"
        splunk-insecureskipverify: "true"
        tag: "{{.Name}}/{{.FullID}}"

volumes:
  data:

secrets:
   env_production:
     file: /opt/.env.production
