version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/mysite.template
      - .:/app
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=9393
      - SERVER_NAME=starreminder.com
    command: /bin/bash -c "envsubst '$$SERVER_PORT $$SERVER_NAME' < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - script
  redis_db:
    image: redis:4.0
    volumes:
      - data:/data
  dogstatsd:
    image: datadog/docker-dd-agent:latest
    ports:
      - "8125:8125/udp"
    environment:
      - SD_BACKEND=docker
      - API_KEY=${DATADOG_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  script:
    image: ifyouseewendy/star-reminder:latest
    build: .
    ports:
      - "9393:9393"
    environment:
      - RACK_ENV=production
      - REDIS_HOST=redis://redis_db:6379
      - DATADOG_HOST=dogstatsd:8125
    volumes:
      - .:/app
      - bundle:/bundle
    depends_on:
      - redis_db
      - dogstatsd

volumes:
  data:
  bundle:
