version: '3'
services:
  redis_db:
    image: redis:4.0
    volumes:
      - data:/data
  dogstatsd:
    image: datadog/docker-dd-agent:latest
    ports:
      - "8125:8125/udp"
    environment:
      - SD_BACKEND=docker
      - API_KEY=${DATADOG_API_KEY}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
  script:
    image: ifyouseewendy/star-reminder:latest
    build: .
    environment:
      - RACK_ENV=production
      - REDIS_HOST=redis://redis_db:6379
      - DATADOG_HOST=dogstatsd:8125
    volumes:
      - .:/app
    depends_on:
      - redis_db
      - dogstatsd

volumes:
  data:
