version: '3.1'
services:
  splunk:
    hostname: splunk
    image: splunk/splunk:6.5.3-monitor
    environment:
      - SPLUNK_START_ARGS=--accept-license --answer-yes --no-prompt
      - SPLUNK_ENABLE_LISTEN=9997
      - SPLUNK_ADD=tcp 1514
      - SPLUNK_USER=root
      - VIRTUAL_HOST=log.starreminder.com
      - VIRTUAL_PORT=8000
    expose:
      - "8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - opt-splunk-etc:/opt/splunk/etc
      - opt-splunk-var:/opt/splunk/var
    ports:
      - "8000:8000"
      - "9997:9997"
      - "8088:8088"
      - "1514:1514"

volumes:
  opt-splunk-etc:
  opt-splunk-var:
